// apps/admin/src/components/shared/Avatar.tsx
import { getInitials } from '@/lib/formatting'
import { cn } from '@/lib/utils'

const SIZE_CLASSES = {
  sm: 'size-6 text-xs',
  md: 'size-9 text-sm',
  lg: 'size-12 text-base',
} as const

export function Avatar({ name, size = 'md' }: { name: string; size?: keyof typeof SIZE_CLASSES }) {
  return (
    <span className={cn('inline-flex items-center justify-center rounded-full bg-avatar-bg font-medium text-avatar-fg', SIZE_CLASSES[size])}>
      {getInitials(name)}
    </span>
  )
}

// apps/blog/src/lib/components/shared/Avatar.svelte
<script lang="ts">
	import { getInitials } from '$lib/utils/initials';

	let {
		name,
		colorClass,
		size = 'md'
	}: { name: string; colorClass: string; size?: 'sm' | 'md' } = $props();

	const sizeClasses = size === 'sm' ? 'h-6 w-6 text-[10px]' : 'h-8 w-8 text-xs';
</script>

<span
	class="inline-flex items-center justify-center rounded-full font-label font-medium text-white {colorClass} {sizeClasses}"
>
	{getInitials(name)}
</span>
